version: '3.9'

services:
  allure-service:
    image: "frankescobar/allure-docker-service"
    container_name: allure-service
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ./reports/allure-result:/app/allure-results
      - ./reports/allure-report:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    container_name: allure-ui
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: http://127.0.0.1:5050
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    depends_on:
      - allure-service
    ports:
      - "5252:5252"